### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by yondu22** [Verssae/flask-tacotron2-tts-web-app#2]
Do you have instructions on how to train, which git commit of tacotron2 to use
I ask because your repo is one of the only few that the models actually work, all the other repos have issues. I want to train a new model and be able to use it with your code

**Comment by Verssae** [comment]
I just trained NVIDIA's Tacotron2 model. All you need can be found in [NVIDIA/Tacotron](https://github.com/NVIDIA/tacotron2). 
You can't training using only my repo. 

If you want to train, just follow NVIDIA's repo.
I trained successfully without big issue.
If you have an issue during training, you can find solutions in NVIDIA's issues.
Instead of my instructions, read NVIDA's README and issues. It will very helpful:)
I
